#!/usr/bin/env python3

import argparse

from artiq.management.pc_rpc import Client


def _get_args():
    parser = argparse.ArgumentParser(description="ARTIQ client")
    parser.add_argument(
        "-o", "--run-once", default=[], nargs=3,
        action="append",
        help="run experiment once. arguments: <path> <name> <timeout>")
    parser.add_argument(
        "-q", "--quit-master", default=False,
        action="store_true",
        help="causes the master to quit")
    return parser.parse_args()


def main():
    args = _get_args()
    remote = Client("::1", 8888)
    try:
        for path, name, timeout in args.run_once:
            remote.run_once(
                {
                    "path": path,
                    "name": name
                }, int(timeout))
        if args.quit_master:
            remote.quit()
    finally:
        remote.close()

if __name__ == "__main__":
    main()
