package:
  name: lit
  version: 0.4.1

source:
  fn: lit-0.4.1.tar.gz
  url: https://pypi.python.org/packages/source/l/lit/lit-0.4.1.tar.gz
  md5: ea6f00470e1bf7ed9e4edcff0f650fe6

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - lit --version

about:
  home: http://llvm.org/docs/CommandGuide/lit.html
  license: MIT
