software:
	make -C /home/artiq-alkaline/ARTIQ-alkaline-fork/artiq_kasli/testbed/software/bootloader CPU=vexriscv
	make -C /home/artiq-alkaline/ARTIQ-alkaline-fork/artiq_kasli/testbed/software/libm CPU=vexriscv-g
	make -C /home/artiq-alkaline/ARTIQ-alkaline-fork/artiq_kasli/testbed/software/libprintf CPU=vexriscv-g
	make -C /home/artiq-alkaline/ARTIQ-alkaline-fork/artiq_kasli/testbed/software/libunwind CPU=vexriscv-g
	make -C /home/artiq-alkaline/ARTIQ-alkaline-fork/artiq_kasli/testbed/software/ksupport CPU=vexriscv-g
	make -C /home/artiq-alkaline/ARTIQ-alkaline-fork/artiq_kasli/testbed/software/libunwind CPU=vexriscv
	make -C /home/artiq-alkaline/ARTIQ-alkaline-fork/artiq_kasli/testbed/software/runtime CPU=vexriscv
