package:
    name: flterm
    version: 0

source:
    git_url: https://github.com/m-labs/misoc
    git_tag: master

about:
    home: https://github.com/m-labs/misoc/blob/master/tools/flterm.c
    license: 3-clause BSD
    summary: 'Serial terminal to connect to MiSoC uart.'
