package:
  name: artiq-dev
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_FULL_HASH", "")[:8] }}

requirements:
  run:
    - python >=3.5.3,<3.6
    - setuptools 33.1.1
    - migen 0.7 py35_2+git40721b2
    - misoc 0.9 py35_6+git5c3ca413
    - jesd204b 0.4
    - microscope
    - binutils-or1k-linux >=2.27
    - llvm-or1k 4.0.1
    - llvmlite-artiq 0.20.0
    - rust-core-or1k 1.23.0 19
    - openocd 0.10.0 4
    - lit
    - outputcheck
    - coverage
    - scipy
    - numpy
    - prettytable
    - asyncserial
    - sphinx 1.4.8
    - sphinx-argparse
    - sphinxcontrib-wavedrom
    - sphinx_rtd_theme
    - h5py
    - python-dateutil
    - pyqt >=5.5
    - quamash
    - pyqtgraph 0.10.0
    - pygit2
    - aiohttp
    - pythonparser >=1.1
    - levenshtein

about:
  home: https://m-labs.hk/artiq
  license: LGPL
  summary: 'ARTIQ development metapackage'
