package:
  name: artiq-dev
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_FULL_HASH", "")[:8] }}

requirements:
  run:
    - python >=3.5.3,<3.6
    - setuptools 33.1.1
    - migen 0.7 py35_0+gite554f07
    - misoc 0.11 py35_0+git3388e6ba
    - jesd204b 0.3
    - binutils-or1k-linux >=2.27
    - llvm-or1k 6.0.0
    - llvmlite-artiq 0.23.0.dev py35_2
    - rust-core-or1k 1.25.0 20
    - openocd 0.10.0 1
    - lit
    - outputcheck
    - coverage
    - scipy
    - numpy
    - prettytable
    - asyncserial
    - sphinx 1.4.8
    - sphinx-argparse
    - sphinxcontrib-wavedrom
    - sphinx_rtd_theme
    - h5py
    - python-dateutil
    - pyqt >=5.5
    - quamash
    - pyqtgraph 0.10.0
    - pygit2
    - aiohttp
    - pythonparser >=1.1
    - levenshtein

about:
  home: https://m-labs.hk/artiq
  license: LGPL
  summary: 'ARTIQ development metapackage'
