package:
  name: sphinx-argparse
  version: 0.1.13

source:
  fn: sphinx-argparse-0.1.13.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinx-argparse/sphinx-argparse-0.1.13.tar.gz
  md5: 5ec84e75e1c4b2ae7ca5fb92a6abd738

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - sphinx
  run:
    - python
    - sphinx

test:
  imports:
    - sphinxarg

about:
  license: MIT
  summary: 'Sphinx extension that automatically documents argparse commands and options'
