
# Autogenerated for the songbird variant
core_addr = "192.168.1.70"

device_db = {
    "core": {
        "type": "local",
        "module": "artiq.coredevice.core",
        "class": "Core",
        "arguments": {
            "host": core_addr,
            "ref_period": 1e-09,
            "analyzer_proxy": "core_analyzer",
            "target": "rv32g",
            "satellite_cpu_targets": {}
        },
    },
    "core_log": {
        "type": "controller",
        "host": "::1",
        "port": 1068,
        "command": "aqctl_corelog -p {port} --bind {bind} " + core_addr
    },
    "core_moninj": {
        "type": "controller",
        "host": "::1",
        "port_proxy": 1383,
        "port": 1384,
        "command": "aqctl_moninj_proxy --port-proxy {port_proxy} --port-control {port} --bind {bind} " + core_addr
    },
    "core_analyzer": {
        "type": "controller",
        "host": "::1",
        "port_proxy": 1385,
        "port": 1386,
        "command": "aqctl_coreanalyzer_proxy --port-proxy {port_proxy} --port-control {port} --bind {bind} " + core_addr
    },
    "core_cache": {
        "type": "local",
        "module": "artiq.coredevice.cache",
        "class": "CoreCache"
    },
    "core_dma": {
        "type": "local",
        "module": "artiq.coredevice.dma",
        "class": "CoreDMA"
    },

    "i2c_switch0": {
        "type": "local",
        "module": "artiq.coredevice.i2c",
        "class": "I2CSwitch",
        "arguments": {"address": 0xe0}
    },
    "i2c_switch1": {
        "type": "local",
        "module": "artiq.coredevice.i2c",
        "class": "I2CSwitch",
        "arguments": {"address": 0xe2}
    },
}

# master peripherals

device_db["led0"] = {
    "type": "local",
    "module": "artiq.coredevice.ttl",
    "class": "TTLOut",
    "arguments": {"channel": 0x000000}
}

device_db["led1"] = {
    "type": "local",
    "module": "artiq.coredevice.ttl",
    "class": "TTLOut",
    "arguments": {"channel": 0x000001}
}

device_db["led2"] = {
    "type": "local",
    "module": "artiq.coredevice.ttl",
    "class": "TTLOut",
    "arguments": {"channel": 0x000002}
}

# DEST#4 peripherals

device_db["core"]["arguments"]["satellite_cpu_targets"][4] = "rv32g"

device_db["songbird0_led0"] = {
    "type": "local",
    "module": "artiq.coredevice.ttl",
    "class": "TTLOut",
    "arguments": {"channel": 0x040000}
}

device_db["songbird0_led1"] = {
    "type": "local",
    "module": "artiq.coredevice.ttl",
    "class": "TTLOut",
    "arguments": {"channel": 0x040001}
}

device_db["songbird0_spi"] = {
    "type": "local",
    "module": "artiq.coredevice.spi2",
    "class": "SPIMaster",
    "arguments": {"channel": 0x040002},
}

device_db["songbird0_config"] = {
    "type": "local",
    "module": "artiq.coredevice.songbird",
    "class": "Config",
    "arguments": {"spi_device": "songbird0_spi", "reset_device": "songbird0_reset"},
}

device_db["songbird0_clear"] = {
    "type": "local",
    "module": "artiq.coredevice.songbird",
    "class": "Clear",
    "arguments": {"channel": 0x040003},
}

device_db["songbird0_reset"] = {
    "type": "local",
    "module": "artiq.coredevice.songbird",
    "class": "Reset",
    "arguments": {"channel": 0x040004},
}

device_db["songbird0_dds0"] = {
    "type": "local",
    "module": "artiq.coredevice.songbird",
    "class": "DDS",
    "arguments": {"bs_channel": 0x040005, "cs_channel": 0x040006},
}

device_db["songbird0_dds1"] = {
    "type": "local",
    "module": "artiq.coredevice.songbird",
    "class": "DDS",
    "arguments": {"bs_channel": 0x040007, "cs_channel": 0x040008},
}

device_db["songbird0_dds2"] = {
    "type": "local",
    "module": "artiq.coredevice.songbird",
    "class": "DDS",
    "arguments": {"bs_channel": 0x040009, "cs_channel": 0x04000a},
}

device_db["songbird0_dds3"] = {
    "type": "local",
    "module": "artiq.coredevice.songbird",
    "class": "DDS",
    "arguments": {"bs_channel": 0x04000b, "cs_channel": 0x04000c},
}

device_db["songbird0_trigger"] = {
    "type": "local",
    "module": "artiq.coredevice.songbird",
    "class": "Trigger",
    "arguments": {"b_channel": 0x04000d, "c_channel": 0x04000e},
}
