package:
  name: pythonparser
  version: 0.0

source:
  git_url: https://github.com/m-labs/pythonparser
  git_tag: master

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

test:
  imports:
    - pythonparser

about:
  home: http://m-labs.hk/pythonparser/
  license: BSD
  summary: 'PythonParser is a Python parser written specifically for use in tooling. It parses source code into an AST that is a superset of Python’s built-in ast module, but returns precise location information for every token.'
