package:
  name: prettytable
  version: !!str 0.7.2

source:
  fn: prettytable-0.7.2.tar.bz2
  url: https://pypi.python.org/packages/source/P/PrettyTable/prettytable-0.7.2.tar.bz2
  md5: 760dc900590ac3c46736167e09fa463a

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - prettytable


about:
  home: http://code.google.com/p/prettytable/
  license:  BSD License
  summary: 'A simple Python library for easily displaying tabular data in a visually appealing ASCII table format.'
