package:
  name: pyelftools
  version: 0.23

source:
  git_url: https://github.com/eliben/pyelftools.git
  git_tag: v0.23

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

test:
  imports:
    - elftools

about:
  home: https://github.com/eliben/pyelftools.git
  license: Public domain
  summary: 'Library for analyzing ELF files and DWARF debugging information'
