package:
  name: artiq
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch_python: true
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}
  entry_points:
    - artiq_client = artiq.frontend.artiq_client:main
    - artiq_compile = artiq.frontend.artiq_compile:main
    - artiq_coreanalyzer = artiq.frontend.artiq_coreanalyzer:main
    - artiq_coreconfig = artiq.frontend.artiq_coreconfig:main
    - artiq_corelog = artiq.frontend.artiq_corelog:main
    - artiq_ctlmgr = artiq.frontend.artiq_ctlmgr:main
    - artiq_gui = artiq.frontend.artiq_gui:main
    - artiq_influxdb = artiq.frontend.artiq_influxdb:main
    - artiq_master = artiq.frontend.artiq_master:main
    - artiq_mkfs = artiq.frontend.artiq_mkfs:main
    - artiq_rpctool = artiq.frontend.artiq_rpctool:main
    - artiq_run = artiq.frontend.artiq_run:main
    - artiq_flash = artiq.frontend.artiq_flash:main
    - lda_controller = artiq.frontend.lda_controller:main
    - novatech409b_controller = artiq.frontend.novatech409b_controller:main
    - pdq2_client = artiq.frontend.pdq2_client:main
    - pdq2_controller = artiq.frontend.pdq2_controller:main
    - thorlabs_tcube_controller = artiq.frontend.thorlabs_tcube_controller:main

requirements:
  build:
    - python >=3.5.1
    - setuptools
    - numpy
    - binutils-or1k-linux
  run:
    - python >=3.5.1
    - llvmlite-artiq 0.10.0.dev py35_20
    - scipy
    - numpy
    - prettytable
    - asyncserial
    - sphinx
    - sphinx-argparse
    - h5py
    - dateutil
    - pyqt5
    - quamash
    - pyqtgraph
    - pygit2
    - aiohttp
    - binutils-or1k-linux
    - pythonparser
    - levenshtein

test:
  imports:
    - artiq

about:
  home: https://m-labs.hk/artiq
  license: GPL
  summary: 'ARTIQ (Advanced Real-Time Infrastructure for Quantum physics) is a next-generation control system for quantum information experiments. It is being developed in partnership with the Ion Storage Group at NIST, and its applicability reaches beyond ion trapping.'
