package:
  name: artiq
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

{% set data = load_setup_py_data() %}

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_FULL_HASH", "")[:8] }}
  entry_points:
    # NOTE: conda-build cannot distinguish between console and gui scripts
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.5.3,<3.6
    - setuptools 33.1.1
  run:
    - python >=3.5.3,<3.6
    - llvmlite-artiq 0.12.0
    - binutils-or1k-linux
    - pythonparser >=1.1
    - openocd 0.10.0+git1
    - lit
    - outputcheck
    - scipy
    - numpy
    - prettytable
    - asyncserial
    - h5py
    - python-dateutil
    - pyqt >=5.5
    - quamash
    - pyqtgraph 0.10.0
    - pygit2
    - aiohttp
    - levenshtein

test:
  imports:
    - artiq

about:
  home: https://m-labs.hk/artiq
  license: LGPL
  summary: 'ARTIQ (Advanced Real-Time Infrastructure for Quantum physics) is a next-generation control system for quantum information experiments. It is being developed in partnership with the Ion Storage Group at NIST, and its applicability reaches beyond ion trapping.'
