package:
  name: libgit2
  version: 0.22.3

source:
  git_url: https://github.com/libgit2/libgit2
  git_tag: v0.22.3

build:
  number: 1

requirements:
  build:
    - system # [linux]
    - cmake # [linux]
    - openssl
    - libssh2
    - zlib
  run:
    - openssl
    - zlib
    - libssh2

about:
  home: https://libgit2.github.com/
  license: GPLv2 with a special Linking Exception
  summary: 'libgit2 is a portable, pure C implementation of the Git core methods provided as a re-entrant linkable library with a solid API, allowing you to write native speed custom Git applications in any language with bindings.'
