[package]
authors = ["M-Labs"]
name = "eh"
version = "0.0.0"

[lib]
name = "eh"
path = "lib.rs"

[dependencies]
cslice = { version = "0.3" }
libc = { path = "../libc" }
unwind = { path = "../libunwind" }
compiler_builtins = "=0.1.39"    # A dependency of alloc, libeh doesn't need it
