package:
    name: llvmlite-artiq
    version: "0.5.1"

source:
    git_url: https://github.com/m-labs/llvmlite
    git_tag: artiq

requirements:
    build:
        - python
        - llvmdev-or1k
        - setuptools
    run:
        - python

build:
    number: 1

test:
    imports:
        - llvmlite_artiq
        - llvmlite_artiq.llvmpy

about:
    home: https://pypi.python.org/pypi/llvmlite/
    license: BSD
