package:
  name: llvmdev-or1k
  version: "3.5.0"

source:
  git_url: https://github.com/openrisc/llvm-or1k
  git_tag: master

build:
  number: 4

requirements:
  build:
    - system [linux]
    - cmake [linux]
  run:
    - system [linux]

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.5.0/LICENSE.TXT)
  summary: Development headers and libraries for LLVM
